#!/bin/bash

# Check if running as root. If root, script will exit
if [[ $EUID -eq 0 ]]; then
    echo "This script should not be executed as root! Exiting......."
    exit 1
fi

cat << EOF
___  ___                  _ _       _     _   
|  \/  |                 | (_)     | |   | |  
| .  . | ___   ___  _ __ | |_  __ _| |__ | |_ 
| |\/| |/ _ \ / _ \| '_ \| | |/ _\` | '_ \| __|
| |  | | (_) | (_) | | | | | | (_| | | | | |_ 
\_|  |_/\___/ \___/|_| |_|_|_|\__, |_| |_|\__|
                               __/ |          
                              |___/                    
EOF